### ISSUE TITLE
LandBOSSE hangs

### ISSUE THREAD

**Issue by akey7** [WISDEM/LandBOSSE#105]
LandBOSSE does not crash. Rather, it hangs with the cores at 100% utilization.

**Comment by parangat94** [comment]
@akey7 , I recently (yesterday) ran into that exact same issue; and I narrowed it down to the part of the code where r_bearing is being calculated. Basically **sympy.solve()** gets lost trying to find a solution for the equation when **b** and **a_eff** have a ton off decimal places (> 10 decimal places). 

So before jumping into solving for **r_bearing**, I rounded off **a_eff** and **e** to a finite number of places (I've been using 1 decimal place for now), and **sympy.solve()** instantly found a solution. 

@eberlea what your thoughts on rounding these variables off to 1 (or more) decimal place(s) before feeding them in the sympy.solve() function?

**Comment by eberlea** [comment]
@parangat94: I think we resolve this issue in our meeting last week (by constraining the simply version) but, for the purposes of documenting my response, I'd say rounding to 2 or 3 decimal places should be fine as well (just in case the version constraint doesn't work, and to potentially reduce solution time).
